sudo: required 

language: go

services:
  - docker

notifications:
    email: false

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - bash ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
